#!/usr/bin/env python3
"""
Generate Go client files for cite/client package.
Avoids write_file tool's \t → \x08 corruption by using Python chr(9).
Usage: python3 generate.go.client.files.py
"""
import os

T = chr(9)
NL = chr(10)
OUT = "/Users/david/Desktop/developments/via54Medit/internal/cite/client"

def write(filename, content_lines):
    path = os.path.join(OUT, filename)
    with open(path, 'w') as f:
        f.write(NL.join(content_lines))
    print(f"  ✓ {filename}: {len(NL.join(content_lines))} bytes")

# ── antafu.go ──────────────────────────────────────
write("antafu.go", [
'package client',
'',
'import (',
T+'"bufio"',
T+'"bytes"',
T+'"context"',
T+'"encoding/json"',
T+'"fmt"',
T+'"io"',
T+'"net/http"',
T+'"os"',
T+'"runtime"',
T+'"strings"',
T+'"sync"',
T+'"time"',
')',
'',
'// AntafuClient queries chat.antafu.com via system browser (human-interactive login).',
'// Requires live browser session for jShield consultData payload.',
'// Set $ANTAFU_TOKEN_FILE to JSON: {Authorization, did-token, consultData}',
'',
'const (',
T+'AntafuBaseURL   = "https://medigw.alipay.com/medigw/aqpc/chat/streamChat"',
T+'AntafuReferer   = "https://chat.antafu.com/"',
T+'AntafuLoginPage = "https://chat.antafu.com/"',
')',
'',
'type SessionTokens struct {',
T+'Authorization string `json:"Authorization"`',
T+'DidToken      string `json:"did-token"`',
T+'ConsultData   string `json:"consultData"`',
T+'AccessToken   string `json:"accessToken"`',
T+'ExpiresAt     int64  `json:"expiresAt"`',
'}',
'',
'type AntafuClient struct {',
T+'baseURL     string',
T+'client      *http.Client',
T+'mu          sync.Mutex',
T+'tokens      *SessionTokens',
T+'browserMode string',
T+'tokenFile   string',
T+'cdpURL      string',
'}',
'',
'func NewAntafuClient() *AntafuClient {',
T+'return &AntafuClient{',
T+T+'baseURL:     AntafuBaseURL,',
T+T+'client:      &http.Client{Timeout: 90 * time.Second},',
T+T+'browserMode: envOr("ANTAFU_BROWSER_OPEN", "once"),',
T+T+'tokenFile:   envOr("ANTAFU_TOKEN_FILE", defaultTokenFile()),',
T+T+'cdpURL:      envOr("ANTAFU_CDP_URL", "http://localhost:9223"),',
T+'}',
'}',
'',
'func envOr(key, def string) string {',
T+'if v := os.Getenv(key); v != "" { return v }',
T+'return def',
'}',
'',
'func defaultTokenFile() string {',
T+'home, err := os.UserHomeDir()',
T+'if err != nil { return "" }',
T+'return home + "/.medit/antafu_tokens.json"',
'}',
'',
'func (c *AntafuClient) IsEnabled() bool {',
T+'return c.tokens != nil && c.tokens.Authorization != ""',
'}',
'',
'func (c *AntafuClient) OpenBrowser(ctx context.Context) {',
T+'switch runtime.GOOS {',
T+'case "darwin":  c.bgExec("open", AntafuLoginPage)',
T+'case "linux":   c.bgExec("xdg-open", AntafuLoginPage)',
T+'case "windows": c.bgExec("cmd", "/c", "start", AntafuLoginPage)',
T+'default:        fmt.Fprintf(os.Stderr, "[antafu] open: %s\\n", AntafuLoginPage)',
T+'}',
T+'fmt.Fprintln(os.Stderr, "[antafu] Browser opened — please log in to chat.antafu.com")',
'}',
'',
'func (c *AntafuClient) bgExec(cmd string, args ...string) {',
T+'go func() {',
T+T+'   p, err := os.StartProcess(cmd, append([]string{cmd}, args...), &os.ProcAttr{})',
T+T+'   if err != nil { fmt.Fprintf(os.Stderr, "[antafu] exec err: %v\\n", err); return }',
T+T+'   p.Wait()',
T+'}()',
'}',
'',
'func (c *AntafuClient) Query(ctx context.Context, query string) (string, error) {',
T+'if !c.IsEnabled() {',
T+T+'return "", fmt.Errorf("antafu not enabled: no session")',
T+'}',
T+'c.mu.Lock()',
T+'defer c.mu.Unlock()',
T+'body := `{"query":"`+query+`"}',
T+'req, err := http.NewRequestWithContext(ctx, "POST", c.baseURL, strings.NewReader(body))',
T+'if err != nil { return "", err }',
T+'req.Header.Set("Content-Type", "application/json")',
T+'req.Header.Set("Authorization", c.tokens.Authorization)',
T+'req.Header.Set("did-token", c.tokens.DidToken)',
T+'req.Header.Set("Referer", AntafuReferer)',
T+'resp, err := c.client.Do(req)',
T+'if err != nil { return "", err }',
T+'defer resp.Body.Close()',
T+'if resp.StatusCode != 200 { return "", fmt.Errorf("HTTP %d", resp.StatusCode) }',
T+'return readSSE(resp.Body)',
'}',
'',
'func readSSE(body io.ReadCloser) (string, error) {',
T+'var parts []string',
T+'scanner := bufio.NewScanner(body)',
T+'scanner.Buffer(make([]byte, 1024*1024), 10*1024*1024)',
T+'for scanner.Scan() {',
T+T+'line := scanner.Text()',
T+T+'if !strings.HasPrefix(line, "data:") { continue }',
T+T+'parts = append(parts, strings.TrimPrefix(line, "data:"))',
T+'}',
T+'if len(parts) == 0 { return "", fmt.Errorf("no SSE data") }',
T+'return strings.Join(parts, "\\n"), nil',
'}',
])

# ── client.go ─────────────────────────────────────
write("client.go", [
'package client',
'',
'import (',
T+'"context"',
T+'"net/http"',
T+'"time"',
')',
'',
'type SearchResult struct {',
T+'Title   string  `json:"title"`',
T+'Authors string  `json:"authors"`',
T+'Journal string  `json:"journal"`',
T+'Year    int     `json:"year"`',
T+'PMID    string  `json:"pmid"`',
T+'DOI     string  `json:"doi"`',
T+'Score   float64 `json:"score"`',
T+'Source  string  `json:"source"`',
'}',
'',
'type Searcher interface {',
T+'Name() string',
T+'Search(ctx context.Context, query string) (*SearchResult, error)',
T+'List(ctx context.Context, query string, limit int) ([]*SearchResult, error)',
'}',
'',
'func NewDefaultHTTPClient() *http.Client {',
T+'return &http.Client{Timeout: 30 * time.Second}',
'}',
])

# ── Verify ────────────────────────────────────────
import subprocess
subprocess.run(["go", "build", "./cmd/medit/..."],
    cwd="/Users/david/Desktop/developments/via54Medit",
    capture_output=True)
print()
print("Build:", "OK" if subprocess.run(
    ["go", "build", "./cmd/medit/..."],
    cwd="/Users/david/Desktop/developments/via54Medit",
    capture_output=True).returncode == 0 else "FAILED")
print("All client files regenerated successfully.")
